### ISSUE TITLE
Bower install in not working under Windows

### ISSUE THREAD

**Issue by Srinivasangovindaraj** [elsix/angular-jointjs-graph-demo#1]
F:\srini\HI\ThirpartyToolForUI\JOINTJSANDANGULARJS\angular-jointjs-graph-demo>bower install
bower angular-jointjs-graph#~0.1.4       not-cached git://github.com/elsix/angular-jointjs-graph.git#~0.1.4
bower angular-jointjs-graph#~0.1.4          resolve git://github.com/elsix/angular-jointjs-graph.git#~0.1.4
bower angular-jointjs-graph#~0.1.4         download https://github.com/elsix/angular-jointjs-graph/archive/0.1.4.tar.gz
bower angular-jointjs-graph#~0.1.4            retry Download of https://github.com/elsix/angular-jointjs-graph/archive/0.1.4.tar.gz failed with EAGAIN, trying with git
bower angular-jointjs-graph#~0.1.4            EPERM EPERM, unlink 'C:\Users\Toshiba\AppData\Local\Temp\Toshiba-PC-Toshiba\bower\angular-jointjs-graph-2096-kvMA8u\archi

Stack trace:
Error: EPERM, unlink 'C:\Users\Toshiba\AppData\Local\Temp\Toshiba-PC-Toshiba\bower\angular-jointjs-graph-2096-kvMA8u\archive.tar.gz'

Console trace:
Trace
    at StandardRenderer.error (C:\Users\Toshiba\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:82:17)
    at Logger.<anonymous> (C:\Users\Toshiba\AppData\Roaming\npm\node_modules\bower\bin\bower:110:22)
    at Logger.EventEmitter.emit (events.js:95:17)
    at Logger.emit (C:\Users\Toshiba\AppData\Roaming\npm\node_modules\bower\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\Toshiba\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:40:20
    at _rejected (C:\Users\Toshiba\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:797:24)
    at C:\Users\Toshiba\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:823:30
    at Promise.when (C:\Users\Toshiba\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:1035:31)
    at Promise.promise.promiseDispatch (C:\Users\Toshiba\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:741:41)
    at C:\Users\Toshiba\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:557:44

System info:
Bower version: 1.3.12
Node version: 0.10.26
OS: Windows_NT 6.1.7601 x64

**Comment by npetkov** [comment]
I don't have a Windows machine available to test right now but I will try to investigate soon. I suspect the issue may be related to the bower issue discussed [here](https://github.com/bower/bower/issues/1006). You may want to try the newest bower version available, 1.4.1.

**Comment by npetkov** [comment]
Just tested on a Windows machine (6.1.7601, x64) with bower 1.4.1 and node 0.12.2 and `bower install` appears to work normally.
